### ISSUE TITLE
Change/Reset Password page design

### ISSUE THREAD

**Issue by AlirezaT99** [Winter-Seminar-Series/WSS-site#151]
We need:
  - one page that can get a token in _url params_ (like `.../..?token=...`) and have a field for a new password and then send it to the reset password api in a POST request with `token` and `password`

  - It's also possible to change password (beside reset). That needs a page with 2 fields for old and new password

Obviously the first one has a higher priority

**Comment by AmooHashem** [comment]
خدایا بسه دیگه

**Comment by Hamedamz** [comment]
من دو تا صفحه رو زدم یکی برای گرفتن ایمیل 
یکی هم برای گرفتن پسورد جدید
@AmooHashem
