### ISSUE TITLE
Fix duration and date in Seminar page

### ISSUE THREAD

**Issue by emranbm** [Winter-Seminar-Series/WSS-site#160]

**Comment by AmooHashem** [comment]
data of these two fields that are given from server, are null but I think they must have value.
چقد انگلیسی نوشتن سخته. اه.

**Comment by emranbm** [comment]
:)))))
فارسی بنویس اوکی

**Comment by emranbm** [comment]
> data of these two fields that are given from server, are null but I think they must have value.

Oh, you're right.

**Comment by ahmadsalimi** [comment]
> data of these two fields that are given from server, are null but I think they must have value.
> چقد انگلیسی نوشتن سخته. اه.

start date has value in https://sharif-wss.ir/api/2020/wss/ , but the end date is not being serialized, which I will serialize it and send a PR for that.

**Comment by AmooHashem** [comment]
> :)))))
> فارسی بنویس اوکی

بذار کلاس کار رو حفظ کنیم

**Comment by emranbm** [comment]
> start date has value in https://sharif-wss.ir/api/2020/wss/ , but the end date is not being serialized, which I will serialize it and send a PR for that.

That's another (non-created yet) issue!
It's about the Seminar object itself

**Comment by AmooHashem** [comment]
> > data of these two fields that are given from server, are null but I think they must have value.
> > چقد انگلیسی نوشتن سخته. اه.
> 
> start date has value in https://sharif-wss.ir/api/2020/wss/ , but the end date is not being serialized, which I will serialize it and send a PR for that.

فکر کنم تو 

> > start date has value in https://sharif-wss.ir/api/2020/wss/ , but the end date is not being serialized, which I will serialize it and send a PR for that.
> 
> That's another (non-created yet) issue!
> It's about the Seminar object itself

Ahsant!

**Comment by emranbm** [comment]
When the time is null, show text: `To be announced ...`
