### ISSUE TITLE
Check corrupted pictures of staffs

### ISSUE THREAD

**Issue by emranbm** [Winter-Seminar-Series/WSS-site#161]
Currently, a staff card that doesn't have a picture, reduce in size to contain only the staff name string.  
But instead, it's better to set a placeholder image to keep such cards aligned with others.

**Comment by AmooHashem** [comment]
اینم اینجوریه که چک می‌کنه اگه استرینگش نال نباشه، عکس پس‌زمینه رو می‌ذاره. اونایی که عکس دارن ولی عکسشون خرابه رو چیکار باید کنم؟

**Comment by emranbm** [comment]
اونایی که عکس دارن ولی خرابه اوکیه اینطرف من چک میکنم

**Comment by AmooHashem** [comment]
حله.
