### ISSUE TITLE
Show status in Registration page: Pending / Successfull

### ISSUE THREAD

**Issue by emranbm** [Winter-Seminar-Series/WSS-site#163]

**Comment by AmooHashem** [comment]
یه نوتیفی میاد که پردازش شما در حال انجام شدنه.
نوتیفی که از بین نمی‌ره تا وقتی خود طرف رو دکمه‌ش بزنه و ببندتش.
این کافی نیست؟

بعدشم نتیجه‌ی عملیات (موفق/شکست) رو بهش نشون میدیم

**Comment by emranbm** [comment]
نه اون حالت رو نمیگم.
همینطوری عادی که طرف میاد تو پیج رجیستر، مشخص باشه که آیا پرداختش اوکی هست یا نه. مثلا اون بالا بنویسه
  
`Your registration for WSS 2020 is successful` or `Your registration for WSS 2020 is pending`

**Comment by emranbm** [comment]
یکی سبز یکی زرد که طرف وضعیت ثبت نامش رو متوجه بشه تو صفحه

**Comment by ahmadsalimi** [comment]
I propose to use bootstrap [badges](https://getbootstrap.com/docs/4.0/components/badge/) for this :)))

**Comment by AmooHashem** [comment]
یه چیز ساده زدم. از بجی که احمد گفته بود استفاده می‌کردم، به هم می‌ریخت ساختارِ سایدبار.
حالا همنیو ببینین، اگه بد بود دوباره بهترش می‌کنیم. اصن به نظرم جای این پیام توی اطلاعیه‌هاست که می‌زنیم به زودی.
