### ISSUE TITLE
Add `Go to class` button in Seminar / Workshop pages

### ISSUE THREAD

**Issue by emranbm** [Winter-Seminar-Series/WSS-site#165]
A button with these behaviors:
- [x] Text: Go to seminar / workshop
- [x] If not logged in, redirect to login page
- [x] If not registered yet, redirect to the registration page, with toast message: `Please register first`
- [x] If the current time is before the event time, toast an info message: `Session not started yet`
- [x] If the current time is after the event time, toast an info message: `Session is ended`
- [x] If none of the above: redirect to the class link.

**Comment by AmooHashem** [comment]
Should I get class links via api?

**Comment by AmooHashem** [comment]
and also, this button is shown for logged in users or registered users?

**Comment by emranbm** [comment]
Yes For both questions :)
