### ISSUE TITLE
Users favorite seminars / workshops

### ISSUE THREAD

**Issue by emranbm** [Winter-Seminar-Series/WSS-site#20]
Users should be able to add seminars/workshops to their favorite.  
One of *important* emails noted at #5 is gonna be these favorites reminders...

**Comment by ahmadsalimi** [comment]
Hi @emranbm.

I think favorite seminars and workshops should be stored in the `Participant` object because seminars and workshops are bounded by the year of the event.

Is that right? If so, I'll start implementing this issue immediately.

**Comment by emranbm** [comment]
> Hi @emranbm.
> 
> I think favorite seminars and workshops should be stored in the `Participant` object because seminars and workshops are bounded by the year of the event.
> 
> Is that right? If so, I'll start implementing this issue immediately.

That's definitely true. :+1:

**Comment by ahmadsalimi** [comment]
This issue is partially resolved by #60
